name: "CI"

on: [push, pull_request]

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci
        working-directory: next-app

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: next-app

  cypress:
    name: Run Cypress E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci
        working-directory: next-app

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: next-app
          start: npm run dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
